# Generated by Django 3.2.19 on 2026-09-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20260901_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1/10 Stars'), (2, '2/10 Stars'), (3, '3/10 Stars'), (4, '4/10 Stars'), (5, '5/10 Stars'), (6, '6/10 Stars'), (7, '7/10 Stars'), (8, '8/10 Stars'), (9, '9/10 Stars'), (10, '10/10 Stars')]),
        ),
    ]
