# Generated by Django 3.2.19 on 2026-09-06 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0006_auto_20260906_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyViewedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['rating'], name='movies_movi_rating_8fd49a_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_date'], name='movies_movi_release_b7ac7d_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['name'], name='movies_movi_name_98114c_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_trending'], name='movies_movi_is_tren_c5976e_idx'),
        ),
        migrations.AddField(
            model_name='recentlyviewedmovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_views', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='recentlyviewedmovie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recentlyviewedmovie',
            index=models.Index(fields=['user', '-viewed_at'], name='movies_rece_user_id_11ee21_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recentlyviewedmovie',
            unique_together={('user', 'movie')},
        ),
    ]
